version: '3'

services:
  pgsql:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'postgres-upload'
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: uploadfiles
